
//teste: requisição para buscar todos os accounts
get http://localhost:3003/accounts
Content-Type: application/json

###

//teste: requisição para buscar account pelo ID
get http://localhost:3003/accounts/a003
Content-Type: application/json

###


###

//teste: requisição para deletar account por id
DELETE  http://localhost:3003/accounts/a003
Content-Type: application/json

###